fn main() {
	println!("--- i8 ---");
	println!("i8::MIN = {}", i8::MIN);
	println!("i8::MAX = {}", i8::MAX);
	println!("--- i16 ---");
	println!("i16::MIN = {}", i16::MIN);
	println!("i16::MAX = {}", i16::MAX);
	println!("--- i32 ---");
	println!("i32::MIN = {}", i32::MIN);
	println!("i32::MAX = {}", i32::MAX);
	println!("--- i64 ---");
	println!("i64::MIN = {}", i64::MIN);
	println!("i64::MAX = {}", i64::MAX);
	println!("--- u8 ---");
	println!("u8::MIN = {}", u8::MIN);
	println!("u8::MAX = {}", u8::MAX);
	println!("--- u16 ---");
	println!("u16::MIN = {}", u16::MIN);
	println!("u16::MAX = {}", u16::MAX);
	println!("--- u32 ---");
	println!("u32::MIN = {}", u32::MIN);
	println!("u32::MAX = {}", u32::MAX);
	println!("--- u64 ---");
	println!("u64::MIN = {}", u64::MIN);
	println!("u64::MAX = {}", u64::MAX);
	println!("--- f32 ---");
	println!("f32::MIN = {}", f32::MIN);
	println!("f32::MAX = {}", f32::MAX);
	println!("--- f64 ---");
	println!("f64::MIN = {}", f64::MIN);
	println!("f64::MAX = {}", f64::MAX);
}
